=== api-evangelist/amazon-proton/json-schema/amazon-proton-service-summary-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/amazon-proton/refs/heads/main/json-schema/amazon-proton-service-summary-schema.json",
  "title": "ServiceSummary",
  "description": "Summary data of an Proton service resource.",
  "type": "object",
  "properties": {
    "arn": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ServiceArn"
        },
        {
          "description": "The Amazon Resource Name (ARN) of the service."
        }
      ]
    },
    "createdAt": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The time when the service was created."
        }
      ]
    },
    "description": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Description"
        },
        {
          "description": "A description of the service."
        }
      ]
    },
    "lastModifiedAt": {
      "allOf": [
        {
          "$ref": "#/components/schemas/Timestamp"
        },
        {
          "description": "The time when the service was last modified."
        }
      ]
    },
    "name": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ResourceName"
        },
        {
          "description": "The name of the service."
        }
      ]
    },
    "status": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ServiceStatus"
        },
        {
          "description": "The status of the service."
        }
      ]
    },
    "statusMessage": {
      "allOf": [
        {
          "$ref": "#/components/schemas/StatusMessage"
        },
        {
          "description": "A service status message."
        }
      ]
    },
    "templateName": {
      "allOf": [
        {
          "$ref": "#/components/schemas/ResourceName"
        },
        {
          "description": "The name of the service template."
        }
      ]
    }
  },
  "required": [
    "arn",
    "createdAt",
    "lastModifiedAt",
    "name",
    "status",
    "templateName"
  ]
}

=== api-evangelist/amazon-proton/examples/amazon-proton-service-summary-example.json
{
  "arn": "arn:aws:proton:us-east-1:123456789:environment/my-env",
  "createdAt": "example-createdAt",
  "description": "example-description",
  "lastModifiedAt": "example-lastModifiedAt",
  "name": "my-environment",
  "status": "ACTIVE",
  "statusMessage": "ACTIVE",
  "templateName": "my-environment"
}
